### ISSUE TITLE
Crash in data-final-fixes

### ISSUE THREAD

**Issue by LovelySanta** [Yousei9/ReStack#10]
Relayed from LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#8:

![Captura](https://user-images.githubusercontent.com/9486307/62159054-25b5d400-b311-11e9-9b41-49f8efbf0e1e.PNG)

The error happens when you search for the rocket launch products:
https://github.com/Yousei9/ReStack/blob/ac1d73394b0d081a6a64d42001694a2cbfa9a4cc/data-final-fixes.lua#L27-L34

Where I changed the launch product:
https://github.com/LovelySanta/FactorioMod-MoreScience/blob/99e9289bf277c1dfd9560be26f120f150098520b/prototypes/recipe/rocket-payloads.lua#L40

I am not sure what exactly goes wrong as I set the launch product exactly as you try to grab it... Logging the item prototype might give you more insight...

**Comment by Yousei9** [comment]
Replied in your own bug report.
https://github.com/LovelySanta/FactorioMod-MoreScience-BobAngelsExtension/issues/8#issuecomment-516719229

**Comment by LovelySanta** [comment]
I got an item that is called "rocketpart-payload-mk1[space-science-pack]" and the amount returning is 1, so this is a valid launch product

**Comment by Yousei9** [comment]
I can't reproduce the original error.
Your launch product is valid for my script. I've added redundant checks anyway.
