### ISSUE TITLE
Steel Plate with AngelBob

### ISSUE THREAD

**Issue by Fuzen777** [Yousei9/ReStack#11]
Hey. So I've read the FAQ and I understand that the changes made by this mod concern categories of items. But then…

With the AngelBob modpack, most stack sizes are pushed to 200, including Steel Plate. But with your mod installed and plates stack size set to 200, Steel Plates sits at 100.

I'm not including a save because it takes a long while to upload and maybe you already know the cause of this, otherwise, just ask and I'll upload one. 
![20190806155453_1](https://user-images.githubusercontent.com/21997472/62545859-c6047f00-b862-11e9-9ffd-dd2295bd3470.jpg)

**Comment by Yousei9** [comment]
I can't say anything without seeing the logfile. Please attach factorio-current.log.

**Comment by Fuzen777** [comment]
Here it is: [factorio-current.log](https://github.com/Yousei9/ReStack/files/3473747/factorio-current.log)

**Comment by Yousei9** [comment]
That's working as intended.
In base plates are grouped by being smelting products. With Bobplates Steel is changed into an intermediate made in special assemblers.

Even if I added checking item subgroups that wouldn't catch steel as bob leaves it in the base "raw-material" subgroup .

**Comment by Fuzen777** [comment]
So that explains. Thanks for the information. 

Good to know that there is an easy way around - and I'll do just that.
