### ISSUE TITLE
Changing only ores changes a bunch of things, and not coal

### ISSUE THREAD

**Issue by pingpong2011** [Yousei9/ReStack#13]
Trying out your mod, I only wanted to change ores. I turned "Ore stack size" to 5000, and everything else to 0.

First, I noticed coal did not change, and thought your mod wasn't working. Then I noticed my other ores changed. I went looking through the mod and base to see how it was supposed to work and tried to figure out what is messing up. I then saw your mod does report stack changes in the log. With only ore size changed, this is what the log reports:
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.copper-cable.stack_size 200 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.iron-ore.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.copper-ore.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.stone.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.uranium-ore.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.sulfur.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.advanced-circuit.stack_size 200 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.battery.stack_size 200 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.electric-engine-unit.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.electronic-circuit.stack_size 200 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.engine-unit.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.explosives.stack_size 50 -> 5000
   9.136 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.iron-gear-wheel.stack_size 100 -> 5000
   9.137 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.iron-stick.stack_size 100 -> 5000
   9.137 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.plastic-bar.stack_size 100 -> 5000
   9.137 Script @__ReStack__/data-final-fixes.lua:49: [RS] Setting ore.processing-unit.stack_size 100 -> 5000

These messages are because I have All Minable - Mine Everything, which adds some intermediates as resource patches. I do not want those changed, and there is potential conflict with other group changes.

Additionally, I have CW-Oceanus installed, and because coal is a product of smelting algae, even though my game is a normal game (not the scenario), the recipe exists and coal is first written by the ore/resource search, and then by the smelting product search. (took me a long time to figure that out - it's also in results, even though it is a singular result)

I have 'fixed' both bugs, but there may be some future issues. Sorry I do not know how to use git and whatever. Also this is my first time writing Lua.

The first fix may mess with other ore subgroups if a mod uses a custom one, but it would be easy enough to add multiple subgroups (and could be used to log who is adding them and/or enable different stack options for those mods).

The second fix is for detecting conflicts, and should work with almost any change (I wasn't sure if I should completely change add_from_item_array. The checker is added to the front of the code, because I wasn't sure if it'd be properly detected later (it probably would work at the end).

Some of this might not be 1:1 if you diff it, because I was adding log messages and things.

In modules\lib.lua:

```
--[[ Copyright (c) 2018 Optera
 * Part of Re-Stack
 *
 * See LICENSE.md in the project directory for license information.
--]]

function ItemIsSafeToChange(item_name)
  --this is a basic check for accidentally overwriting another stack change
  --true for no conflict, false for conflict (if-good-else-bad)

  if ReStack_Items[item_name] and ReStack_Items[item_name].stack_size and ReStack_Items[item_name].stack_size ~= 0 then
    log("ReStack warning! We're changing the stack size of " .. item_name .. " more than once!")
    log("This happens because an item is part of more than one group we're changing. A mod may be the cause of this.")
    return false
  end
  return true
end

function add_from_item_array(items, stack_size, category)
  for _, item in pairs(items) do
    if item.name and ( not item.type or item.type == "item") then
      if ItemIsSafeToChange(item.name) then
        ReStack_Items[item.name] = {stack_size = stack_size, type = category}
      end
    elseif item[1] then
      ReStack_Items[item[1]] = {stack_size = stack_size, type = category}
    end
  end
end

-- sets stacks for items associated with an entity or resource
function SelectItemByEntity(ent_type, stack_size, category)
  category = category or ent_type
  for _, entity in pairs(data.raw[ent_type]) do
    -- log(serpent.dump(entity))
    if entity.minable then
      if entity.minable.result then
        if category == "resource" or category == "ore" then
          if _G.data.raw["item"][entity.minable.result] then
            --a mod can add "ore" that is actually a more complex item - we only want to change ORES
            if _G.data.raw["item"][entity.minable.result].subgroup and _G.data.raw["item"][entity.minable.result].subgroup == "raw-resource" then
              --log("Found ore: " .. entity.minable.result .. " and it looks like a normal ore. Changing stack size.")
              ReStack_Items[entity.minable.result] = {stack_size = stack_size, type = category}
              --log("stack size: " .. stack_size .. " category: " .. category)
            else
              --log("Found ore: " .. entity.minable.result .. " but it looks like it is not a normal ore (it is not a raw-resource). Leaving stack unchanged.")
            end
          else
            --log("Found ore: " .. entity.minable.result .. " but it is not an item. Leaving stack unchanged.")
          end
        else
          --we are not checking resources/ores
          ReStack_Items[entity.minable.result] = {stack_size = stack_size, type = category}
        end
      elseif entity.minable.results then
        add_from_item_array(entity.minable.results, stack_size, category)
      end
    end
  end

end

-- set stacks for recipe results (used only by smelting)
function SelectItemsByRecipeResult(recipe, stack_size, category)
  local item

  if recipe.result then
    if ItemIsSafeToChange(recipe.result) then
      ReStack_Items[recipe.result] = {stack_size = stack_size, type = category}
    end
  end
  if recipe.normal and recipe.normal.result then
    if ItemIsSafeToChange(recipe.normal.result) then
      ReStack_Items[recipe.normal.result] = {stack_size = stack_size, type = category}
    end
  end
  if recipe.expensive and recipe.expensive.result then
    if ItemIsSafeToChange(recipe.expensive.result) then
      ReStack_Items[recipe.expensive.result] = {stack_size = stack_size, type = category}
    end
  end

  if recipe.results then
    add_from_item_array(recipe.results, stack_size, category)
  end
  if recipe.normal and recipe.normal.results then
    add_from_item_array(recipe.normal.results, stack_size, category)
  end
  if recipe.expensive and recipe.expensive.results then
    add_from_item_array(recipe.expensive.results, stack_size, category)
  end
end

-- set stack for all recipe input items (used only by rocket parts)
function SelectItemsByRecipeInput(recipe, stack_size, category)
  if recipe.ingredients then
    add_from_item_array(recipe.ingredients, stack_size, category)
  end
  if recipe.normal and recipe.normal.ingredients then
    add_from_item_array(recipe.normal.ingredients, stack_size, category)
  end
  if recipe.expensive and recipe.expensive.ingredients then
    add_from_item_array(recipe.expensive.ingredients, stack_size, category)
  end
end

function DumpRestackTableChanges(category)
  for item_name, stack_data in pairs(ReStack_Items) do
    log("item name in restack list: " .. item_name)

    if stack_data.stack_size then
      log("stack size assigned: " .. stack_data.stack_size)
    else
      log(item_name .. " has no stack size assigned")
    end
  end
end


```

####

Code is released with your licensing restrictions or whatever. I don't care. (a thank you would be nice tho and I'd like some credit :( )

I think those are the only changes I made for it to work in both respects, with the helper function added to dump a specific category. A comment on how the mod works: all items are added to the stack tables initially and are checked/changed repeatedly. Instead, items should only be added to the stack table on request, and perhaps removed if assigneable, and then report any orphan stacks (if explicit) or failed assignments afterwards (assignments paths that did nothing). The full-copy is easily noticeable when a category is dumped (it wasn't significant for loading for me, just worth bringing up.

Additionally, we don't need to even check certain groups if the value is set to 0. I never would've encountered the coal bug if smelting recipes weren't checked when 0.

(I would've used a 'continue' in the ore-but-not-really section but Lua doesn't have one! Tiny bit of duplicating the stack assignment expression)

**Comment by pingpong2011** [comment]
None of it looks right (sorry, thought formatting would be preserved - it didn't look right in code tags either).

https://drive.google.com/open?id=1uyYLlN3OWHn7I_eZODgTypsoxIJiKqed

https://pastebin.com/1kX48jTx

**Comment by Yousei9** [comment]
ReStack was made to work with vanilla and mods retaining vanilla mechanics like AngelBob.
If a total conversion changes item types around that's not my problem. To work with something like that I'd have to get rid of auto detection of types and use name lists for each setting.

As for your pull request, I'm not going to spend hours piecing together all your changes from multiple sources and test them against all mods currently working properly with ReStack.
