### ISSUE TITLE
Problem with barrel capacity of 500

### ISSUE THREAD

**Issue by bobbun** [Yousei9/ReStack#14]
I was experiencing a lot of frustration with barrels--the recipes were functioning in groups of five--so after reading the mod description more closely I decided to set the barrel capacity to 500, supposing based on the behavior described that this would make barreling recipes work with single barrels.  Imagine my surprise when this attempt backfired, and the recipes were adjusted to work with barrels ten at a time, meaning that to do anything with barrels I would need to work in units of 5000 fluid at a time.  This looks like a bug.  In particular, it looks like line 21 of barrel.lua, which reads:

if barrel_capacity < 500 then -- each recipe should at least process the base 50L

should instead read

if barrel_capacity <= 500 then -- each recipe should at least process the base 50L

As an aside, there are a lot of ways for barrels to get separated and this approach creates a lot of in game clean-up issues.  I'm not well versed in Factorio modding but, if possible, wouldn't changing the amount of time the recipe takes to process be a more straightforward way of accomplishing the stated goal of 500L/2s than tinkering with the number of barrels involved in each operation?  That approach would also allow the mod to work as intended if someone were to, say, set the barrel capacity to 1000.

**Comment by Yousei9** [comment]
> wouldn't changing the amount of time the recipe takes to process be a more straightforward way of accomplishing the stated goal of 500L/2s than tinkering with the number of barrels involved in each operation?

Factorio can only handle 1 recipe/tick. Using speed modules and beacons on 0.2s recipes quickly runs into this hard cap.

Performance is another reason to use batch recipes. Crafting batches of 100 in one 20s recipe requires 99 calculations less than crafting 1 piece in a 0.2s recipe 100 times.

Finally even after the 0.16.8 capacity change, barrels are already ridiculously broken in base. 
Transported with bots they have infinite throughput. 
Used as storage in 9 chests a 3x3 area can store 4320l while a fluid tank can only store 1000l.
My calculations are based on reducing barrel capacity to realistic 1-10l. If anything allowing capacities above 50l is an oversight on my part and would be removed.
