### ISSUE TITLE
[0.18] Crash on Startup

### ISSUE THREAD

**Issue by vizthex123** [Yousei9/ReStack#15]
I get this an error whenever, log file attached.
Disabling the mod makes it work fine, but this is one of my favorite mods so I was wondering if you could take a look at it

[factorio-current.log](https://github.com/Yousei9/ReStack/files/4749341/factorio-current.log)

**Comment by Yousei9** [comment]
Which mods create and modify undarl-gas-deuterium-barrel?

**Comment by Yousei9** [comment]
Should now skip over invalid/unsupported energy strings.
Resulting fuel values WILL be wrong.

**Comment by vizthex123** [comment]
Yeah it's been fixed, wow that was fast. Thanks!
