### ISSUE TITLE
Crash in 0.3.11

### ISSUE THREAD

**Issue by flexoo** [Yousei9/ReStack#2]
![screenshot](https://user-images.githubusercontent.com/13826740/35408493-383837ec-0207-11e8-9a1e-c718325d376f.jpg)

**Comment by Yousei9** [comment]
I'm unable to reproduce this but with 0.3.11.

**Comment by flexoo** [comment]
I updated from 0.3.9 to 0.3.11 then it crash when loading new


[mod-list.txt](https://github.com/Yousei9/ReStack/files/1665469/mod-list.txt)

**Comment by Yousei9** [comment]
Yeah I'm not going to find out what mod interferres one by one.
Run this debug version and post factorio-current.log

[ReStack_0.3.11.zip](https://github.com/Yousei9/ReStack/files/1665479/ReStack_0.3.11.zip)

**Comment by flexoo** [comment]
:D no problem, here the log.
[factorio-current.log](https://github.com/Yousei9/ReStack/files/1665495/factorio-current.log)

**Comment by Yousei9** [comment]
One of your mods seems to adds an empty ingredient list to rocket parts.
I'm surprised factorio's lua parser doesn't simply remove empty lists like that.

Added another check against that.

**Comment by flexoo** [comment]
hm that can only be either bobs or Spacemod.
thanks for fix, will try out.

**Comment by flexoo** [comment]
just tested and works fine again, thank you :)
