### ISSUE TITLE
How to configure for headless server

### ISSUE THREAD

**Issue by dochoss** [Yousei9/ReStack#21]
I know this is a long shot with the last release being 4 years ago, but any way I could get a little help configuring this for a headless server? I tried changing the default values in the `settings.lua` file, but the values seem to be reset to the mod default values when launching the game. I also just tried setting the `item.stack_size` manually in the loop in `data-final-fixes`, but that has the same result. Any help would be appreciated!

**Comment by Yousei9** [comment]
I have no experience with headless. 
settings.lua is the only place where default values are set, but those are only applied the first time a mod is activated, or when reset to default (which I guess you can't do on headless).
Better ask in general Factorio forum.

**Comment by dochoss** [comment]
Gotcha. Thanks for the quick response!
