### ISSUE TITLE
Stone not being effected. 

### ISSUE THREAD

**Issue by delciotto** [Yousei9/ReStack#8]
Stone doesn't seem to be getting affected by settings like it did in .16. I have msot bob and angels mods installed, but i had the same mod list as .16 and it worked back then.

**Comment by Yousei9** [comment]
Works fine for me.
Attach the complete factorio-current.log file.

**Comment by delciotto** [comment]
[factorio-current.log](https://github.com/Yousei9/ReStack/files/3026347/factorio-current.log)

**Comment by Yousei9** [comment]
Looks like one of your mods removes base stone, iron and copper.

**Comment by delciotto** [comment]
Yeah, I just checked in a test map. none of bob or angel's ores you get from processing saphirite/jivolite/stiratite/crotinnium/rubyte/bobmonium work in .17, they worked in .16. Well that sucks.
